<a href="https://colab.research.google.com/github/tdmhub/L4DA_resources/blob/main/TaskAnalysisOf_DataL4DAT37.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction
This is a task to practise the skis you learnt in the tutorial t combine data

In [85]:
# Importing library
import pandas as pd
# Set numbers for how many rows and columns will be displayed
pd.set_option('display.min_rows', 10) #default will be 10
pd.set_option('display.max_columns', 20)
url='https://github.com/tdmhub/L4DA_resources/raw/main/online_store_customer_data.csv'
df_Store = pd.read_csv(url)
df_Store

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,1.0,1199.79
4,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2507,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2508,5/1/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,5/1/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,5/1/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [86]:
df_Store.isna().sum().sort_values(ascending=False)

Amount_spent        242
Referal             155
Age                  42
Gender               28
Employees_status     26
Transaction_date      0
Transaction_ID        0
Marital_status        0
State_names           0
Segment               0
Payment_method        0
dtype: int64

In [87]:
df_Store_NA=df_Store.dropna(subset=["Amount_spent"],inplace=True)
df_Store

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,1.0,1199.79
5,1/3/2019,151205,Male,71.0,Single,Hawaii,Basic,Employees,PayPal,1.0,2922.66
...,...,...,...,...,...,...,...,...,...,...,...
2507,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2508,5/1/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,5/1/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,5/1/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [88]:
df_Store.isna().sum().sort_values(ascending=False)

Referal             142
Age                  39
Gender               26
Employees_status     25
Transaction_date      0
Transaction_ID        0
Marital_status        0
State_names           0
Segment               0
Payment_method        0
Amount_spent          0
dtype: int64

In [89]:
df_Store_NA_Gender=df_Store.copy()
df_Store_NA_Gender.dropna(subset=["Gender"],inplace=True)

In [90]:
df_Store_NA_Gender.isna().sum().sort_values(ascending=False)

Referal             140
Age                  39
Employees_status     25
Transaction_date      0
Transaction_ID        0
Gender                0
Marital_status        0
State_names           0
Segment               0
Payment_method        0
Amount_spent          0
dtype: int64

In [91]:
df_Store_NA_Employees_status=df_Store.copy()
df_Store_NA_Employees_status.dropna(subset=["Employees_status"],inplace=True)
df_Store_NA_Employees_status.isna().sum().sort_values(ascending=False)

Referal             141
Age                  39
Gender               26
Transaction_date      0
Transaction_ID        0
Marital_status        0
State_names           0
Segment               0
Employees_status      0
Payment_method        0
Amount_spent          0
dtype: int64

In [92]:
df_Store_NA_Age=df_Store.copy()
df_Store_NA_Age.dropna(subset=["Age"],inplace=True)
df_Store_NA_Age.isna().sum().sort_values(ascending=False)

Referal             139
Gender               26
Employees_status     25
Transaction_date      0
Transaction_ID        0
Age                   0
Marital_status        0
State_names           0
Segment               0
Payment_method        0
Amount_spent          0
dtype: int64

In [93]:
df_Store_NA_Gender.duplicated().sum()

11

In [94]:
df_Store_NA_Gender.drop_duplicates(keep='first',inplace=True)

In [95]:
df_Store_NA_Genderpivot=df_Store_NA_Gender.pivot(index='Transaction_ID',columns='Gender',values='Amount_spent')
df_Store_NA_Genderpivot

Gender           Female     Male
Transaction_ID
151200          2051.36      NaN
151201              NaN   544.04
151202              NaN  1572.60
151205              NaN  2922.66
151206          1481.42      NaN
...                 ...      ...
153694              NaN   286.82
153695           150.10      NaN
153696           708.88      NaN
153697              NaN  2030.07
153699              NaN  1073.15

[2233 rows x 2 columns]

In [96]:
df_Store_NA_Genderpivot.fillna(0)
df_Store_NA_Genderpivot

Gender           Female     Male
Transaction_ID
151200          2051.36      NaN
151201              NaN   544.04
151202              NaN  1572.60
151205              NaN  2922.66
151206          1481.42      NaN
...                 ...      ...
153694              NaN   286.82
153695           150.10      NaN
153696           708.88      NaN
153697              NaN  2030.07
153699              NaN  1073.15

[2233 rows x 2 columns]

In [97]:
df_Store_NA_Genderpivot_sum=df_Store_NA_Genderpivot.sum()
df_Store_NA_Genderpivot_sum

Gender
Female    1733893.09
Male      1438001.72
dtype: float64

In [98]:
df_Store_NA_Genderpivot=df_Store_NA_Genderpivot.fillna(0)
df_Store_NA_Genderpivot

Gender           Female     Male
Transaction_ID
151200          2051.36     0.00
151201             0.00   544.04
151202             0.00  1572.60
151205             0.00  2922.66
151206          1481.42     0.00
...                 ...      ...
153694             0.00   286.82
153695           150.10     0.00
153696           708.88     0.00
153697             0.00  2030.07
153699             0.00  1073.15

[2233 rows x 2 columns]

In [99]:
df_Store_NA_Age.duplicated().sum()

11

In [100]:
df_Store_NA_Age.isna().sum().sort_values(ascending=False)

Referal             139
Gender               26
Employees_status     25
Transaction_date      0
Transaction_ID        0
Age                   0
Marital_status        0
State_names           0
Segment               0
Payment_method        0
Amount_spent          0
dtype: int64

In [101]:
df_Store_NA_Age

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,1.0,1199.79
5,1/3/2019,151205,Male,71.0,Single,Hawaii,Basic,Employees,PayPal,1.0,2922.66
...,...,...,...,...,...,...,...,...,...,...,...
2507,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2508,5/1/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,5/1/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,5/1/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [102]:
df_Store_NA_Age.drop_duplicates(keep='first',inplace=True)
df_Store_NA_Age_lt20=df_Store_NA_Age.where(df_Store_NA_Age.Age<20)
df_Store_NA_Age_lt20V2=df_Store_NA_Age_lt20.dropna()
df_Store_NA_Age_lt20V2

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200.0,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
15,1/6/2019,151215.0,Male,16.0,Single,New York,Platinum,workers,Other,1.0,1005.92
33,1/14/2019,151233.0,Male,15.0,Married,Missouri,Gold,self-employed,Card,1.0,628.93
42,1/17/2019,151242.0,Female,16.0,Single,Texas,Gold,self-employed,PayPal,1.0,938.16
50,1/22/2019,151250.0,Female,16.0,Married,Maryland,Silver,Employees,PayPal,1.0,583.72
...,...,...,...,...,...,...,...,...,...,...,...
2440,4/9/2021,153628.0,Female,18.0,Married,Virginia,Basic,self-employed,PayPal,1.0,2777.01
2441,4/9/2021,153629.0,Male,18.0,Single,Alabama,Platinum,Employees,Card,0.0,289.85
2461,4/15/2021,153649.0,Male,15.0,Single,Kansas,Basic,workers,PayPal,1.0,2901.98
2474,4/19/2021,153662.0,Male,15.0,Married,Washington,Basic,Employees,PayPal,1.0,1285.46
2502,4/29/2021,153690.0,Male,16.0,Single,Louisiana,Basic,self-employed,PayPal,0.0,1171.23

In [103]:
df_Store_NA_Age_lt20V2Pivot=df_Store_NA_Age_lt20V2.pivot(index='Transaction_ID',columns='Age',values='Amount_spent')
df_Store_NA_Age_lt20V2Pivot

Age                15.0     16.0  17.0     18.0     19.0
Transaction_ID
151200.0            NaN      NaN   NaN      NaN  2051.36
151215.0            NaN  1005.92   NaN      NaN      NaN
151233.0         628.93      NaN   NaN      NaN      NaN
151242.0            NaN   938.16   NaN      NaN      NaN
151250.0            NaN   583.72   NaN      NaN      NaN
...                 ...      ...   ...      ...      ...
153628.0            NaN      NaN   NaN  2777.01      NaN
153629.0            NaN      NaN   NaN   289.85      NaN
153649.0        2901.98      NaN   NaN      NaN      NaN
153662.0        1285.46      NaN   NaN      NaN      NaN
153690.0            NaN  1171.23   NaN      NaN      NaN

[159 rows x 5 columns]

In [104]:
df_Store_NA_Age_lt20V2Pivot.fillna(0)
df_Store_NA_Age_lt20V2Pivotsum=df_Store_NA_Age_lt20V2Pivot.sum()
df_Store_NA_Age_lt20V2Pivotsum

Age
15.0    51721.15
16.0    50386.33
17.0    36009.01
18.0    56456.18
19.0    41007.96
dtype: float64